# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind "%"

# Reload config file with Prefix + r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "✓ tmux.conf reloaded!"

# Switch panes using Alt+HJKL
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

unbind "Up"
unbind "Down"
unbind "Left"
unbind "Right"

# Enable mouse control
set -g mouse on

# Window management
set-option -g allow-rename off
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# ==========================================
# TrueColor & Terminal Capabilities
# ==========================================
# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,alacritty:RGB"

# ==========================================
# Make copy work like vi
# ==========================================
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# setting for pi
set -g extended-keys on
set -g extended-keys-format csi-u

